# Generated by Django 4.2.3 on 2023-08-10 06:56

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specs',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст'),
        ),
    ]
