# Generated by Django 4.2.3 on 2023-08-10 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('specs', '0002_alter_specs_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='specs',
            name='moderator_nickname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Модератор'),
        ),
    ]
