# Generated by Django 4.2.3 on 2023-08-13 04:26

from django.db import migrations, models
import specs.models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0003_specs_moderator_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specs',
            name='image',
            field=models.ImageField(blank=True, upload_to=specs.models.PathAndRename('images'), verbose_name='Картинка'),
        ),
    ]
