# Generated by Django 4.2.3 on 2023-08-13 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0005_tagslugmodify'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TagSlugModify',
        ),
    ]
