# Generated by Django 4.2.3 on 2023-08-13 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0007_tagslugmodify'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TagSlugModify',
        ),
    ]
