# Generated by Django 4.2.3 on 2023-08-15 04:31

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0008_delete_tagslugmodify'),
    ]

    operations = [
        migrations.AddField(
            model_name='specs',
            name='preview',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default=True, verbose_name='Превью'),
        ),
    ]
