# Generated by Django 4.2.3 on 2023-08-15 04:32

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0009_specs_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specs',
            name='preview',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Превью'),
        ),
    ]
