# Generated by Django 4.2.3 on 2023-08-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0010_alter_specs_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='specs',
            name='view_preview_post',
            field=models.BooleanField(default=True, verbose_name='Показывать превью в конце поста'),
        ),
    ]
