# Generated by Django 4.2.3 on 2023-08-15 06:36

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0011_specs_view_preview_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specs',
            name='preview',
            field=embed_video.fields.EmbedVideoField(blank=True, verbose_name='Превью'),
        ),
    ]
