# Generated by Django 4.2.3 on 2023-08-22 22:23

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0013_remove_specs_preview_alter_specs_view_preview_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='specs',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(default=True, verbose_name='Описание'),
        ),
    ]
