# Generated by Django 4.2.3 on 2023-08-22 22:23

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0014_specs_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specs',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание'),
        ),
    ]
