# Generated by Django 4.2.3 on 2023-08-05 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='default_avatar.png', null=True, upload_to='users_images'),
        ),
    ]
